In [1]:
import pandas as pd

# Graph Plot

In [2]:
def wer(sentence1, sentence2):
    from Levenshtein import distance as ld
    sen1, sen2 = str(sentence1), str(sentence2)
    norLen = max(len(sen1), len(sen2))
    return ld(sen1,sen2)/norLen

In [3]:
def calculate_processed_wer(list_input):
    import math
    n = len(list_input)
    print("n is ",n)
    percentWer = []
    for i in range(1,101):
        till_num = math.ceil(0.01 * i * n)
#         print("till_num is ",till_num," for i as ",i)
#         print("i is ",i," till_num is ",till_num)
        cum_sum = 0
        for j in range(till_num):
            cum_sum += list_input[j]
        percentWer.append(cum_sum/till_num)
    
    return percentWer

In [4]:
def cdf_wer_plot(appWer, ivrWer):
    import matplotlib.pyplot as plt
    import matplotlib.ticker as plticker
    import numpy as np
    nAudio = len(appWer)
    fig, ax = plt.subplots()
    ax.set_xlabel("Word Error Rate")
    ax.set_ylabel("Percentage of audio files(%)")
    
    audio = np.arange(1,101)
    
#     appWer.sort()
#     ivrWer.sort()
    #Here is how cdf starts
#     x=np.arange(1,nAudio)
#     frequency=np.array([3,8,4,5,3,6])
#     pdf=frequency/np.sum(frequency)
#     cdf=np.cumsum(pdf)
    #Here is how the cdf ends
#     appWer.sort()
#     ivrWer.sort()

    
    appWer.sort()
    ivrWer.sort()
    
    appWerProcessed = calculate_processed_wer(appWer)
    ivrWerProcessed = calculate_processed_wer(ivrWer)
    
#     appWerProcessed.sort()
#     ivrWerProcessed.sort()
    
    appPdf = appWerProcessed/np.sum(appWerProcessed)
    ivrPdf = ivrWerProcessed/np.sum(ivrWerProcessed)
    
    
    appCdf = np.cumsum(appPdf)
    ivrCdf = np.cumsum(ivrPdf)
    
    ax.plot(appCdf, audio, color = 'red', label = 'Through Application')
    ax.plot(ivrCdf, audio, color = 'blue', label = 'Through IVR')
    loc = plticker.MultipleLocator(base=0.1)
    ax.xaxis.set_major_locator(loc)
    ax.legend()
    plt.savefig('Comparsion_cdf')
    plt.show()

# App Data

In [19]:
import pandas as pd
appData = pd.read_excel('app_data.xlsx')
q1 = appData[appData['Question']=='कृपया अपना नाम बताएं |']
q2 = appData[appData['Question']=='आप कहाँ रहते हैं?']
q3 = appData[appData['Question']=='आपके परिवार में कुल कितने लोग हैं?']
q4 = appData[appData['Question']=='क्या आप या आपके परिवर में कोई महिला गर्भवती है?']
q5 = appData[appData['Question']=='गर्भवती महिला का कौनसा महीना चल रहा है?']
q6 = appData[appData['Question']=='सवास्थ्य कर्मी या डॉक्टर के अनुसार गर्भवती महिला की आनुमानिक डिलीवरी का महीना कौन सा है?']
q7 = appData[appData['Question']=='आपके कितना बच्चे है? अपने जवाब में बच्चों की कुल संख्या बताएँ|']
q8 = appData[appData['Question']=='सबसे छोटे बच्चे की उम्र कितनी है?']
q9 = appData[appData['Question']=='बच्चे की जनम की तारीख क्या है?']

In [20]:
# appRemain = appData[ ( (appData['Question']!='कृपया अपना नाम बताएं |') 
#  & (appData['Question']!='आप कहाँ रहते हैं?') 
#  & (appData['Question']!='आपके परिवार में कुल कितने लोग हैं?')
#  & (appData['Question']!='क्या आप या आपके परिवर में कोई महिला गर्भवती है?') 
#  & (appData['Question']!='गर्भवती महिला का कौनसा महीना चल रहा है?') 
#  & (appData['Question']!='सवास्थ्य कर्मी या डॉक्टर के अनुसार गर्भवती महिला की आनुमानिक डिलीवरी का महीना कौन सा है?') 
#  & (appData['Question']!='आपके कितना बच्चे है? अपने जवाब में बच्चों की कुल संख्या बताएँ|') 
#  & (appData['Question']!='सबसे छोटे बच्चे की उम्र कितनी है?')
#  & (appData['Question']!='बच्चे की जनम की तारीख क्या है?'))]

In [21]:
sttAppData = pd.concat([q2['STT transcription'],q3['STT transcription'],q4['STT transcription'],q5['STT transcription'],q6['STT transcription'],q7['STT transcription'],q8['STT transcription'],q9['STT transcription']]).tolist()
manualAppData = pd.concat([q2['Moderator transcription'],q3['Moderator transcription'],q4['Moderator transcription'],q5['Moderator transcription'],q6['Moderator transcription'],q7['Moderator transcription'],q8['Moderator transcription'],q9['Moderator transcription']]).tolist()

In [22]:
print(appData.shape)

(173, 9)


In [9]:
appWer = []
for i in range(len(sttAppData)):
    appWer.append(wer(sttAppData[i],manualAppData[i]))

# IVR Data

In [11]:
import pandas as pd
d1 = pd.read_excel('vb1.xlsx')
d2 = pd.read_excel('vb2.xlsx')
d3 = pd.read_excel('round3.xlsx')
d4 = pd.read_excel('r4.xlsx')
d1Temp = d1[['STT transcription','Moderator Transcription']]
d2Temp = d2[['STT transcription','Moderator Transcription']]
d3Temp = d3[['STT transcription','Moderator Transcription']]
d4Temp = d4[['STT transcription','Moderator Transcription']]
frames = [d1Temp, d2Temp, d3Temp, d4Temp]
ivrData = pd.concat(frames)
print(ivrData.shape)

(2656, 2)


In [12]:
sttIvrData = ivrData['STT transcription'].tolist()
manualIvrData = ivrData['Moderator Transcription'].tolist()

In [13]:
ivrWer = []
for i in range(len(sttIvrData)):
    ivrWer.append(wer(sttIvrData[i],manualIvrData[i]))

In [14]:
print(len(ivrWer))

2656


In [15]:
cdf_wer_plot(appWer, ivrWer)

n is  140
n is  2656


<Figure size 640x480 with 1 Axes>

# Data Preperation

In [2]:
r4Data = pd.read_excel('r4.xlsx')
r4Final = r4Data[r4Data['STT transcription'].notnull()]

In [3]:
print(r4Data.shape)
print(r4Final.shape)

(614, 15)
(365, 15)


In [4]:
childR4 = r4Final[r4Final['Question']=='Aapke kitne bachche hai Aapna jawab mein bachchon ki kul sankhya bataye?']
familyR4 = r4Final[r4Final['Question']=='Aapke parivar mein kul kitne log rehte hain?']
pregWomanR4 = r4Final[r4Final['Question']=='Garbhvati  mahila ka kaunsa mahina chal raha hai?']
dobRound4 = r4Final[r4Final['Question']=='Bachche ki janam ki tarikh kya hai']
haaNaR4 = r4Final[r4Final['Question']=='Kya aap ya aapke parivar me koi mahila garbhvati hai?']
umraR4 = r4Final[r4Final['Question']=='Sabse chote bacche ki umar kitni hai']

noOfChildrenR4 = childR4[['Question','Ground truth entity','DF entity','STT transcription','Moderator Transcription']]
totalFamilyR4 = familyR4[['Question','Ground truth entity','DF entity','STT transcription','Moderator Transcription']]
monthsPregnantR4 = pregWomanR4[['Question','Ground truth entity','DF entity','STT transcription','Moderator Transcription']]
dobR4 = dobRound4[['Question','Ground truth entity','DF entity','STT transcription','Moderator Transcription']]
yesNoR4 = haaNaR4[['Question','Ground truth entity','DF entity','STT transcription','Moderator Transcription']]
ageR4 = umraR4[['Question','Ground truth entity','DF entity','STT transcription','Moderator Transcription']]

# totalFamilyR4.to_excel('totalFamilyR4.xlsx')
# noOfChildrenR4.to_excel('noOfChildrenR4.xlsx')
# monthsPregnantR4.to_excel('monthsPregnantR4.xlsx')
# dobR4.to_excel('dobR4.xlsx')
# yesNoR4.to_excel('yesNoR4.xlsx')
# ageR4.to_excel('ageR4.xlsx')

# Date of Birth

In [112]:
dobR12 = pd.read_excel('dobTrain.xlsx')
dobR12 = dobR12[['Question','Ground truth entity','DF entity','STT transcription','Moderator Transcription','Quality']]
dobR3 = pd.read_excel('dobRound3.xlsx')
dobR3 = dobR3[['Question','Ground truth entity','DF entity','STT transcription','Moderator Transcription','Quality']]
dobR4 = pd.read_excel('dobR4.xlsx')
dobR4 = dobR4[['Question','Ground truth entity','DF entity','STT transcription','Moderator Transcription','Quality']]

In [113]:
print(dobR12.shape, dobR3.shape, dobR4.shape)

(112, 6) (131, 6) (28, 6)


In [114]:
def near_str(word1, word2):
    import textdistance as td
    word1 = str(word1)
    word2 = str(word2)
    return td.levenshtein.normalized_similarity(word1, word2)

def checkInSen(word, sentence):
    word = str(word)
    sentence = str(sentence)
    for pos_words in sentence.split():
        if near_str(word, pos_words) >= 0.65:
            return True
    return False

def findDate(sentence):
    sentence = str(sentence)
    import json
    outSentence = {'Date':'-1','Month':'-1','Year':'-1'}

    rawMonths=['जनवरी','फरवरी','मार्च','अप्रैल','मई','जून','जुलाई','अगस्त','सितंबर','अक्टूबर','नवंबर','दिसंबर']
    rawMonthsDict = {i:j%12+1 for (j,i) in enumerate(rawMonths)}
    hindiMonths=['चैत्र','बैसाख','ज्येष्ठ','आषाढ़','सावन','भाद्रपद','आश्विन','कार्तिक','अग्रहायण','पौष','माघ','फाल्गुन']
    hindiMonthsDict = {i:((j+3)%12+1) for (j,i) in enumerate(hindiMonths)}
    hindiMonthPrefix=['पहला','दूसरा','तीसरा','चौथा','पांचवां','छठा','सातवां','आठवां','नौवां','दसवां','ग्यारहवां','बारहवां']
    hindiMonthPrefixDict = {i:j%12+1 for (j,i) in enumerate(hindiMonthPrefix)}

    #Now for date and month
    flag=0
    for month in rawMonths:
        if month in sentence:
            outSentence['Month']=str(rawMonthsDict[month])
            flag=1
            break
            

    #Now checking for months in hindi
    if flag==0:
        for month in hindiMonths:
            if month in sentence:
                outSentence['Month']=str(hindiMonthsDict[month]) 
                flag=1
                break
    
    
    
    item=sentence.replace("-"," ").replace("/"," ").split()
    
    for i in range(len(item)):
        item[i]= item[i].lstrip('0')
    
    # Near string matching for rawMonths
    
    if flag==0:
        for senWords in item:
            for month in rawMonths:
                if near_str(senWords,month) >= 0.65:
                    outSentence['Month'] = str(rawMonthsDict[month])
                    flag = 1
                    break
            
            if flag==1:
                break
    
    # Near String Matching for hindiMonths
    if flag==0:
        for senWords in item:
            for month in hindiMonths:
                if near_str(senWords, month) >= 0.65:
                    outSentence['Month'] = str(hindiMonthsDict[month])
                    flag = 1
                    break
            
            if flag==1:
                break
        

    # Now for hindi prefix like pehla mahina, dusra mahine, teesra mahina and continued till 12th months

    if(len(item)>=2):
        for i in range(len(item)-1):
            if checkInSen(item[i], hindiMonthPrefix) and (near_str(item[i+1],'महीना') >= 0.65 or near_str(item[i+1],'महिना')
                                                >= 0.65):
                if flag==0:
                    outSentence['Month'] =  hindiMonthPrefixDict[item[i]] #item[i]
                    flag=1
                    break

#     total+=len(item)
    
    
    
    #For Months
    if(len(item)>=2):
        for i in range(len(item)-1):
                if item[i].isdigit() and item[i+1].isdigit() and len(item[i])!=4 and len(item[i+1])!=4:
                    if flag==0:
                        if (int(item[i+1])) <= 12:
                            outSentence['Month'] =  str(int(item[i+1])) #item[i+1]
                            flag=1
                            break
                elif item[i].isdigit() and item[i+1].isdigit() and len(item[i])!=4 and len(item[i+1])==4:
                    if flag==0:
                        if len(item[i])==1 and int(item[i])!=0:
                            outSentence['Month'] = str(int(item[i])) #item[i]
                            flag=1
                            break
                        elif len(item[i])==3:
                            if int(item[i][:2]) <= 31 and int(item[i][2]) != 0:
                                outSentence['Month'] =  str(int(item[i][2])) #item[i][2]
                                flag = 1
                                break
                            elif int(item[i][:2]) <= 31 and int(item[i][2]) == 0:
                                if int(item[i][1])==1:
                                    outSentence['Month'] =  str(int(item[i][1:])) #item[i][1:]
                                    flag = 1
                                    break
                        elif len(item[i])==2:
                            if int(item[i])<=12:
                                outSentence['Month'] =  str(int(item[i])) #item[i]
                                flag=1
                                break
                            else:
                                outSentence['Month'] =  str(int(item[i][1])) #item[i][1]
                                flag = 1
                                break
                        else:
                            z = 2 #dummy

                elif item[i].isdigit() and item[i+1].isdigit() and len(item[i])==4 and len(item[i+1])==4:
                    if flag==0:
                        if int(item[i+1]) <= 2100 and int(item[i+1]) >= 1900:
                            if int(item[i][2:]) <= 12:
                                outSentence['Month'] =  str(int(item[i][2:])) #item[i][2:]
                                flag = 1
                                break
                else:
                    z=2 #Dummy

#     if truthMonths[-1]==1:
#         trainMonthOut.append(1)
#     else:
#         trainMonthOut.append(0)

    flagDate=0
    if len(item)>=2:
        for i in range(len(item)-1):
                if item[i].isdigit() and item[i+1].isdigit() and len(item[i])!=4 and len(item[i+1])!=4:
                    if flagDate==0:
                        outSentence['Date'] = item[i]
                        flagDate=1
                        break
                elif item[i].isdigit() and len(item[i])!=4 and not item[i+1].isdigit() and int(item[i])<32:
                    if flagDate==0:
                        suppList = ["साल","महीना","महिना"]
                        if not(item[i+1] in suppList):
                            outSentence['Date'] = item[i]
                            flagDate=1
                            break
                elif item[i].isdigit() and item[i+1].isdigit() and len(item[i])!=4 and len(item[i+1])==4:
                    if flagDate==0:
                        if len(item[i])==3:
                            if int(item[i][:2]) <= 31 and int(item[i][2]) != 0:
                                outSentence['Date'] = item[i][:2]
                                flagDate = 1
                                break
                            elif int(item[i][:2]) <= 31 and int(item[i][2]) == 0:
                                if int(item[i][1])==1:
                                    outSentence['Date'] = item[i][0]
                                    flagDate = 1
                                    break
                        elif len(item[i])==2:
                            if int(item[i])<=12:
                                z = 2 #Do  nothing
                            else:
                                outSentence['Date'] = item[i][0]
                                flagDate = 1
                                break
                        else:
                            z = 2 #dummy
                elif item[i].isdigit() and item[i+1].isdigit() and len(item[i])==4 and len(item[i+1])==4:
                    if flagDate==0:
                        if int(item[i+1]) <= 2100 and int(item[i+1]) >= 1900:
                            if int(item[i][2:]) <= 12:
                                outSentence['Date'] = item[i][:2]
                                flagDate = 1
                                break
                else:
                    z=2
    elif len(item) == 1:
        try:
            if type(int(item[0]))==int:
                if int(item[0]) <= 31:
                    outSentence['Date'] = item[0]
                    flagDate = 1
        except:
            z = 2 # Basically do nothing

    ##############################################################################################
    flagYear=0
    for items in sentence.replace("-"," ").split():
        try:
            if len(items) == 4 and int(items) > 1900 and int(items) < 2100:
                outSentence['Year'] = items
                flagYear=1
                break
        except:
            z=2 #Dummy z
    if flagYear!=1:
        words = sentence.replace("-"," ").split()
        for i in range(len(words)-2):
            try:
                if (type(int(words[i])) == int)  and (type(int(words[i+1]))==int) and (type(int(words[i+2]))==int):
                    if len(words[i+2])==2:
                        if int(words[i+2]) > 50:
                            outSentence['Year'] = "19"+words[i+2]
                        else:
                            outSentence['Year'] = "20"+words[i+2]
                        flagYear = 1
                        break
            except:
                z=2
    if flagYear!=1:
        words = sentence.replace("-"," ").split()
        for i in range(len(words)-1):
            if words[i] in rawMonths or words[i] in hindiMonths or words[i] in hindiMonthPrefix:
                if words[i+1].isdigit() and len(words[i+1])==2:
                    if int(words[i+1])>=50:
                        outSentence['Year'] = "19"+str(words[i+1])
                    else:
                        outSentence['Year'] = "20"+str(words[i+1])
                    flagYear =1
                    break

#     json_Output = json.dumps(outSentence,ensure_ascii=False)
    return outSentence

In [115]:
print(dobR12.shape, dobR3.shape, dobR4.shape)

(112, 6) (131, 6) (28, 6)


In [116]:
dobData = pd.concat([dobR12, dobR3, dobR4])
print(dobData.shape)
dobData = dobData[dobData['Quality']==1]
print(dobData.shape)

(271, 6)
(198, 6)


In [117]:
# Yaha Apne Module ka
import datetime
dateOut, monthOut, yearOut = [], [], []


for text in dobData['STT transcription']:
    if type(text)==datetime.datetime:
        tempDate = datetime.datetime.date(text)
        text = tempDate.strftime("%d-%m-%Y")
    
    out = findDate(text)
    dateOut.append(out['Date'])
    monthOut.append(out['Month'])
    yearOut.append(out['Year'])

In [118]:
dobAct = dobData['Ground truth entity'].to_numpy()

In [119]:
# print(dobAct)
import datetime
for i in range(len(dobAct)):
    if type(dobAct[i])==datetime.datetime:
        dobAct[i] = dobAct[i].strftime('%d/%m/%Y')

In [120]:
dateAct , monthAct , yearAct = [], [], []
for item in dobAct:
    item = str(item)
    l = item.split('/')
    if len(l)==1:
        dateAct.append(str(-1))
        monthAct.append(str(-1))
        yearAct.append(str(-1))
    elif len(l)==2:
        dateAct.append(str(-1))
        monthAct.append(str(int(l[0])))
        yearAct.append(str(int(l[1])))
    else:
        dateAct.append(str(int(l[0])))
        monthAct.append(str(int(l[1])))
        yearAct.append(str(int(l[2])))
# print(dateAct)
# print(monthAct)
# print(yearAct)

In [121]:
from sklearn.metrics import accuracy_score
print("Date Accuracy is ", accuracy_score(dateAct, dateOut))
print("Month Accuracy is ", accuracy_score(monthAct, monthOut))
print("Year Accuracy is ", accuracy_score(yearAct, yearOut))

Date Accuracy is  0.9595959595959596
Month Accuracy is  0.8787878787878788
Year Accuracy is  0.9242424242424242


In [122]:
l1DateAct = [0 if item=='-1' else 1 for item in dateAct]
l1MonthAct = [0 if item=='-1' else 1 for item in monthAct]
l1YearAct = [0 if item=='-1' else 1 for item in yearAct]

l1DateOut = [0 if item=='-1' else 1 for item in dateOut]
l1MonthOut = [0 if item=='-1' else 1 for item in monthOut]
l1YearOut = [0 if item=='-1' else 1 for item in yearOut]

In [112]:
from sklearn.metrics import precision_score, f1_score, recall_score, accuracy_score, confusion_matrix

In [124]:
print(precision_score(l1DateAct,l1DateOut))
print(f1_score(l1DateAct, l1DateOut))
print(recall_score(l1DateAct, l1DateOut))
print(accuracy_score(l1DateAct, l1DateOut))

1.0
0.9947643979057591
0.9895833333333334
0.98989898989899


In [125]:
print(precision_score(l1MonthAct,l1MonthOut))
print(f1_score(l1MonthAct, l1MonthOut))
print(recall_score(l1MonthAct, l1MonthOut))
print(accuracy_score(l1MonthAct, l1MonthOut))

0.9943181818181818
0.9536784741144414
0.9162303664921466
0.9141414141414141


In [126]:
print(precision_score(l1YearAct,l1YearOut))
print(f1_score(l1YearAct, l1YearOut))
print(recall_score(l1YearAct, l1YearOut))
print(accuracy_score(l1YearAct, l1YearOut))

0.994413407821229
0.9700272479564034
0.9468085106382979
0.9444444444444444


In [127]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(l1DateAct, l1DateOut))
print(confusion_matrix(l1MonthAct, l1MonthOut))
print(confusion_matrix(l1YearAct, l1YearOut))

[[  6   0]
 [  2 190]]
[[  6   1]
 [ 16 175]]
[[  9   1]
 [ 10 178]]


<b> Dialogflow for DateOfBirth </b>

In [128]:
# Yahan DialogFlow ka for round 1 & 2
import json
dobR12 = dobR12[dobR12['Quality']==1]
dobDF = dobR12['DF entity'].tolist()
dobDialogFlow = []
for pred in dobDF:
        try:
            ent = json.loads(pred)
            dobDialogFlow.append(str(list(ent['entity'][0].values())[0]))
        except:
            dobDialogFlow.append("#")

In [129]:
dateDFOut, monthDFOut, yearDFOut = [], [], []
for sentence in dobDialogFlow:
    sentence = sentence.replace('/','-')
#     print(sentence)
    if sentence=='#':
        dateDFOut.append(-1)
        monthDFOut.append(-1)
        yearDFOut.append(-1)
    else:
        here = sentence.split('-')
        dateDFOut.append(str(int(here[2])))
        monthDFOut.append(str(int(here[1])))
        yearDFOut.append(str(int(here[0])))

In [130]:
print(len(dateDFOut))
print(len(monthDFOut))
print(len(yearDFOut))

90
90
90


In [131]:
# Yahan dialogflow ka for round3 and round4
dobR3 = dobR3[dobR3['Quality']==1]
dobR4 = dobR4[dobR4['Quality']==1]

dobDF = pd.concat([dobR3['DF entity'],dobR4['DF entity']]).tolist()
import datetime
for i in range(len(dobDF)):
    if type(dobDF[i])==datetime.datetime:
        dobDF[i] = dobDF[i].strftime('%m/%d/%Y')
        

for sentence in dobDF:
    sentence = str(sentence)
    sentence = sentence.replace('/','-')

    if sentence=='NOENTITY' or sentence=='nan':
#         print('aaya kya')
        dateDFOut.append(str(-1))
        monthDFOut.append(str(-1))
        yearDFOut.append(str(-1))
    else:
        here = sentence.split('-')
        if len(here)==1:
            dateDFOut.append(str(here[0]))
            monthDFOut.append(str(-1))
            yearDFOut.append(str(-1))
        else:
            dateDFOut.append(str(int(here[1])))
            monthDFOut.append(str(int(here[0])))
            yearDFOut.append(str(int(here[2])))
            
# print(che)

In [132]:
# Replacing 5555 with -1 as 5555 was placed in place of -1 for dialogflow
for i in range(len(dateDFOut)):
    if dateDFOut[i]=='5555':
        dateDFOut[i]='-1'
    if monthDFOut[i]=='5555' :
        monthDFOut[i] = '-1'
    if yearDFOut[i]=='5555':
        yearDFOut[i] = '-1'

In [133]:
print("Date Accuracy for dialogflow is ",accuracy_score(dateAct, dateDFOut))
print("Month Accuracy for dialogflow is ",accuracy_score(monthAct, monthDFOut))
print("Year Accuracy for dialogflow is ", accuracy_score(yearAct, yearDFOut))

Date Accuracy for dialogflow is  0.7828282828282829
Month Accuracy for dialogflow is  0.7777777777777778
Year Accuracy for dialogflow is  0.7222222222222222


In [134]:
l1DFDateOut = [0 if item=='-1' else 1 for item in dateDFOut]
l1DFMonthOut = [0 if item=='-1' else 1 for item in monthDFOut]
l1DFYearOut = [0 if item=='-1' else 1 for item in yearDFOut]

In [135]:
print(precision_score(l1DateAct,l1DFDateOut))
print(f1_score(l1DateAct, l1DFDateOut))
print(recall_score(l1DateAct, l1DFDateOut))
print(accuracy_score(l1DateAct, l1DFDateOut))

0.9651162790697675
0.9120879120879122
0.8645833333333334
0.8383838383838383


In [136]:
print(precision_score(l1MonthAct,l1DFMonthOut))
print(f1_score(l1MonthAct, l1DFMonthOut))
print(recall_score(l1MonthAct, l1DFMonthOut))
print(accuracy_score(l1MonthAct, l1DFMonthOut))

0.9593023255813954
0.9090909090909092
0.8638743455497382
0.8333333333333334


In [137]:
print(precision_score(l1YearAct,l1DFYearOut))
print(f1_score(l1YearAct, l1DFYearOut))
print(recall_score(l1YearAct, l1DFYearOut))
print(accuracy_score(l1YearAct, l1DFYearOut))

0.9479768786127167
0.9085872576177285
0.8723404255319149
0.8333333333333334


In [138]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(l1DateAct, l1DFDateOut))
print(confusion_matrix(l1MonthAct, l1DFMonthOut))
print(confusion_matrix(l1YearAct, l1DFYearOut))

[[  0   6]
 [ 26 166]]
[[  0   7]
 [ 26 165]]
[[  1   9]
 [ 24 164]]


# Number

In [168]:
# !pip install stanza
import stanza
# stanza.download('hi')
hi_nlp = stanza.Pipeline('hi', processors='tokenize,lemma,pos,depparse', verbose=False, use_gpu=False)

In [169]:
import re
import textdistance as td
import difflib

def findAge(sentence):
#     print(sentence)
    thresh = 0.65
    sentence.replace(',',' ')
    sentence.replace(':',' ')
    sentence.replace('.',' ')
    sentence.replace('_',' ')
    sentence = sentence.strip()
#     print('sentence baad me hua ',sentence)
    age = -1
    confd = 1
    hindiNum = ['जीरो','एक' ,'दो' ,'तीन' ,'चार' ,'पांच' ,'छः' ,'सात'   ,'आठ' ,'नौ' ,'दस' , 'ग्यारह' ,'बारह','तेरह','चौदह',
 'पंद्रह','सोलह','सत्रह','अट्ठारह' ,'उन्निस' ,'बीस','इक्कीस','बाईस','तेईस','चौबीस' ,'पच्चीस' ,'छब्बीस','सत्ताईस','अट्ठाईस' ,'उनतीस','तीस' ,'इकतीस' ,
 'बत्तीस','तैंतीस','चौंतीस' ,'पैंतीस','छ्त्तीस' ,'सैंतीस','अड़तीस' ,'उनतालीस' ,'चालीस' ,'इकतालीस' ,'बयालीस','तैंतालीस','चौंतालीस' ,
 'पैंतालीस' ,'छियालीस' ,'सैंतालीस','अड़तालीस','उनचास', 'पचास','इक्याबन' ,'बावन','तिरेपन','चौबन','पचपन', 'छप्पन','सत्तावन',
'अट्ठावन','उनसठ','साठ','इकसठ','बासठ','तिरसठ','चौंसठ','पैंसठ','छियासठ' ,'सड़सठ','अड़सठ','उनहत्तर','सत्तर' ,'इकहत्तर' ,
'बहत्तर','तिहत्तर','चौहत्तर' ,'पचहत्तर','छिहत्तर' ,'सतहत्तर' ,'अठहत्तर' ,'उनासी' ,'अस्सी' ,'इक्यासी' ,'बयासी','तिरासी' ,'चौरासी' ,
 'पचासी' ,'छियासी' ,'सतासी' ,'अठासी' ,'नवासी' ,'नब्बे' ,'इक्यानबे' ,'बानवे' ,'तिरानवे' ,'चौरानवे' ,'पचानवे' ,'छियानवे' ,'सत्तानवे' ,
 'अट्ठानवे' ,'निन्यानवे' ,'सौ']
    
    dictHindi = dict()
    
    # Just assigning numeral values to the hindi letters
    count = 0
    for word in hindiNum:
        dictHindi[word] = count
        count += 1
    
    dictHindi['छे'] = 6
    
    for words in sentence.split():
#         print('words kya aaya isme ', words)
        if age!=-1:
            break
        try:
            if(type(int(words))==int):
#                 print('isme aaya kya')
                if(int(words) >= 0 and int(words) <= 1000):
                    age = int(words)
#                     print('age kya hua finally ',age)
        except:
            z = 2
            
    suffix = ['वी','टी','वा']
    
    if age==-1:
        words = sentence.split()
        for word in words:
            for pos_word in hindiNum:
                first = td.levenshtein.normalized_similarity(pos_word, word)
                second = td.levenshtein.normalized_similarity(pos_word+suffix[0], word)
                third = td.levenshtein.normalized_similarity(pos_word+suffix[1], word)
                fourth = td.levenshtein.normalized_similarity(pos_word+suffix[2], word)
                confd = max(confd, first, second, third, fourth)
                if first >= thresh:
                    return (dictHindi[pos_word],first)
                elif second >= thresh or third >= thresh or fourth >= thresh:
                    return (dictHindi[pos_word],max(second, third, fourth))
                
        
        for word in words:
            if word=='छे':
                return (6,1)
    
    return age,confd

In [170]:
def posTagging(sentence):
    hi_doc = hi_nlp(sentence)
    for sent in hi_doc.sentences:
        out = []
        for word in sent.words:
            if word.pos=='NUM':
               out.append(word.text) 
        return out

In [171]:
def checkZero(sentence):
    import re
    import textdistance as td
    import difflib
    thresh = 0.65
    noList = [ 'नहीं' , 'ना', 'नाही']
    words = sentence.split()
    for word in words:
        if word in noList:
            return 1
        else:
            for pos_word in noList:
                if td.levenshtein.normalized_similarity(pos_word, word) >= thresh:
                    return 1
    return 0

In [172]:
def findNumeralData(sentence):
    cZero = checkZero(sentence)
    if cZero==1:
        return (0,1)
    out = posTagging(sentence)
#     print(out)|
    x = len(out)
#     print(x)
    if x == 0:
#         print(out)
        return findAge(sentence)
    else:
        res = -1
        confd = 1
        for agla in out:
#             print(agla)
            res,confd = findAge(agla)
            if res!=-1:
                break
    return res,confd

In [173]:
# This code is for months pregnant with slight modification
import re
import textdistance as td
import difflib

thresh = 0.65

possible_words = {'शून्य':0,'एक':1,'दो':2,'तीन':3,'चार':4,'पांच':5,'छः':6,'सात':7,'आठ':8,'नौ':9,'लास्ट':9,'पहला':1,
                  'दूसरा':2,'तीसरा':3,'चौथा':4,'पांचवा':5,'छत्ता':6,'चट्टा':6,'सातवा':7,'आठवा':8,'नौंवा':9,'नवा':9,'शुरू':1,
                  'नाना':9}
suffix = ['वी','टी','वा']
general_words = {'हां':1,'हाँ':1,'सब':9,'नहीं':0,'ना':0}

def get_digits(word):
    if not re.search('\d+', word):
        # no digits from 0-9
        if not re.search('[०१२३४५६७८९]+', word):
            return -1
        return re.search('[०१२३४५६७८९]+', word).group()
    return re.search('\d+', word).group()

def get_month(sent):    # Similar to get education
    sent = str(sent)
    sent = sent.strip()
    words = sent.split()
    for word in words:
        digits = get_digits(word)
        if digits != -1:
            return int(digits)
        for pos_word in possible_words:
            if td.levenshtein.normalized_similarity(pos_word, word) >= thresh:
                return possible_words[pos_word]
            elif td.levenshtein.normalized_similarity(pos_word+suffix[0], word) >= thresh\
             or td.levenshtein.normalized_similarity(pos_word+suffix[1], word) >= thresh\
             or td.levenshtein.normalized_similarity(pos_word+suffix[2], word) >= thresh:
                return possible_words[pos_word]
        for gen_word in general_words:
            if gen_word == word:    # It is better to have exact match here
#                 print(word, gen_word)
                return general_words[gen_word]
    return -1

In [174]:
# mp stands for month pregnant

mp12 = pd.read_excel('monthsPregnantR12.xlsx')
mp3 = pd.read_excel('monthsPregnantR3.xlsx')
mp4 = pd.read_excel('monthsPregnantR4.xlsx')

print(mp12.shape, mp3.shape, mp4.shape)

(27, 7) (17, 7) (18, 7)


In [175]:
monthsPregnant = pd.concat([mp12, mp3, mp4])
print(monthsPregnant.shape)
# monthsPregnant = monthsPregnant[monthsPregnant['Quality']==1]
# print(monthsPregnant.shape)

(62, 7)


In [176]:
months_pregnant_out = []
for text in monthsPregnant['STT transcription']:
    text = str(text)
    a = get_month(text)
    months_pregnant_out.append(a)

In [177]:
months_pregnant_gt = monthsPregnant['Ground truth entity']
months_pregnant_act = []

for item in months_pregnant_gt:
    try:
        if (type(int(item)) == int):
            months_pregnant_act.append(int(item))
    except:
            months_pregnant_act.append(-1)

In [178]:
months_pregnant_df = monthsPregnant['DF entity']
months_pregnant_dfOut = []
for item in months_pregnant_df:
    try:
        if (type(int(item)) == int):
            months_pregnant_dfOut.append(int(item))
    except:
            months_pregnant_dfOut.append(-1)

In [179]:
print(len(months_pregnant_out), len(months_pregnant_act), len(months_pregnant_dfOut))

62 62 62


In [182]:
l1Act, l2Act = [], []
for item in months_pregnant_gt:
    try:
        if (type(int(item)) == int):
            l1Act.append(1)
            l2Act.append(int(item))
    except:
            l1Act.append(0)
            l2Act.append(-1)

l1Out = []
for item in months_pregnant_out:
    if item==-1:
        l1Out.append(0)
    else:
        l1Out.append(1)

In [185]:
l1Out = []
for item in months_pregnant_dfOut:
    if item==-1:
        l1Out.append(0)
    else:
        l1Out.append(1)

In [186]:
from sklearn.metrics import accuracy_score, precision_score, f1_score, recall_score, confusion_matrix
print(precision_score(l1Act,l1Out))
print(f1_score(l1Act,l1Out))
print(recall_score(l1Act, l1Out))
print("Presence Identification accuracy is ",accuracy_score(l1Act, l1Out))
print("Correctness accuracy is ",accuracy_score(l2Act,months_pregnant_out))

1.0
0.8750000000000001
0.7777777777777778
Presence Identification accuracy is  0.8064516129032258
Correctness accuracy is  0.8225806451612904


In [187]:
print(confusion_matrix(l1Act, l1Out))

[[ 8  0]
 [12 42]]


<b>Error Analysis </b>

In [162]:
# Error Points for our Module
import numpy as np
l2Act = np.asarray(l2Act)
months_pregnant_out = np.asarray(months_pregnant_out)
indexing = l2Act!=months_pregnant_out
errorPoints = monthsPregnant[indexing]['STT transcription'].to_numpy()
print(len(errorPoints))
print(errorPoints)
print(l2Act[indexing])
print(months_pregnant_out[indexing])

15
['लास्ट महीना' 'नवा महीना चल रहा है' 'नाना' 'छठा महीना' 'दूसरा महीना'
 'छठा महीना चल रहे हैं' 'दूसरा महीना चल रहा है' 'नवा महीना' 'दूसरा महीना'
 'नहीं गर्भवती महिला नहीं है मेरे पास' 'तीसरा' 'तीसरा'
 '9 महीना हो ना हो तनी' 'छठा महीना' 'मेरा घर में कोई नहीं है वैसा']
[ 9  9  9  6  2  6  2  9  2 -1  3  3  9  6 -1]
[-1  0 -1 -1 -1 -1 -1  0 -1  0 30 30  0 -1  0]


<b>#############################################################################</b>

In [279]:
nc12 = pd.read_excel('noOfChildrenR12.xlsx')
nc3 = pd.read_excel('noOfChildrenR3.xlsx')
nc4 = pd.read_excel('noOfChildrenR4.xlsx')

print(nc12.shape, nc3.shape, nc4.shape)

(165, 7) (158, 7) (56, 7)


In [280]:
noOfChildren = pd.concat([nc12, nc3, nc4])
print(noOfChildren.shape)
# noOfChildren = noOfChildren[noOfChildren['Quality']==1]
# print(noOfChildren.shape)

(379, 7)


In [281]:
noOfChildren_out = []
for text in noOfChildren['STT transcription']:
    text = str(text)
    a, b = findNumeralData(text)
    noOfChildren_out.append(a)

In [282]:
noOfChildren_gt = noOfChildren['Ground truth entity']
noOfChildren_act = []

for item in noOfChildren_gt:
    try:
        if (type(int(item)) == int):
            noOfChildren_act.append(int(item))
    except:
            noOfChildren_act.append(-1)

In [283]:
noOfChildDf = []
import json
# nc12 = nc12[nc12['Quality']==1]
noOfChildren_df12 = nc12['DF entity'].tolist()
for pred in noOfChildren_df12:
        try:
            ent = json.loads(pred)
            noOfChildDf.append(str(list(ent['entity'][0].values())[0]))
        except:
            noOfChildDf.append("#")
            
noOfChildren_dfOut = [-1 if item=='#' else int(item) for item in noOfChildDf]

In [284]:
# nc3 = nc3[nc3['Quality']==1]
# nc4 = nc4[nc4['Quality']==1]
noOfChildren_df34 = pd.concat([nc3['DF entity'], nc4['DF entity']]).tolist()
for item in noOfChildren_df34:
    try:
        if (type(int(item))==int):
            noOfChildren_dfOut.append(int(item))
    except:
        noOfChildren_dfOut.append(-1)

In [285]:
print(len(noOfChildren_out), len(noOfChildren_act), len(noOfChildren_dfOut))

379 379 379


In [286]:
l1Act, l2Act = [], []
for item in noOfChildren_gt:
    try:
        if (type(int(item)) == int):
            l1Act.append(1)
            l2Act.append(int(item))
    except:
            l1Act.append(0)
            l2Act.append(-1)

l1Out = []
for item in noOfChildren_out:
    if item==-1:
        l1Out.append(0)
    else:
        l1Out.append(1)

In [289]:
l1Out = []
for item in noOfChildren_dfOut:
    if item==-1:
        l1Out.append(0)
    else:
        l1Out.append(1)

In [290]:
from sklearn.metrics import accuracy_score, precision_score, f1_score, recall_score, confusion_matrix
print(precision_score(l1Act,l1Out))
print(f1_score(l1Act,l1Out))
print(recall_score(l1Act, l1Out))
print("Presence Identification accuracy is ",accuracy_score(l1Act, l1Out))
print("Correctness accuracy is ",accuracy_score(l2Act,noOfChildren_dfOut))

0.9968354430379747
0.9264705882352942
0.8653846153846154
Presence Identification accuracy is  0.8680738786279684
Correctness accuracy is  0.8073878627968337


In [291]:
print(confusion_matrix(l1Act, l1Out))

[[ 14   1]
 [ 49 315]]


<b>#####################################################################</b>

In [309]:
# tf stands for total family
# 967 - 748 Ignore it

tf12 = pd.read_excel('totalFamilyR12.xlsx')
tf3 = pd.read_excel('totalFamilyR3.xlsx')
tf4 = pd.read_excel('totalFamilyR4.xlsx')

print(tf12.shape, tf3.shape, tf4.shape)

(204, 7) (224, 7) (98, 7)


In [311]:
totalFamily = pd.concat([tf12, tf3, tf4])
print(totalFamily.shape)
# totalFamily = totalFamily[totalFamily['Quality']==1]
# print(totalFamily.shape)

(526, 7)


In [312]:
totalFamily_out = []
for text in totalFamily['STT transcription']:
    text = str(text)
    a, b = findNumeralData(text)
    totalFamily_out.append(a)

In [313]:
totalFamily_gt = totalFamily['Ground truth entity']
totalFamily_act = []

for item in totalFamily_gt:
    try:
        if (type(int(item)) == int):
            totalFamily_act.append(int(item))
    except:
            totalFamily_act.append(-1)

In [314]:
totalFamilyDF = []
import json
# tf12 = tf12[tf12['Quality']==1]
totalFamily_df12 = tf12['DF entity'].tolist()
for pred in totalFamily_df12:
        try:
            ent = json.loads(pred)
            totalFamilyDF.append(str(list(ent['entity'][0].values())[0]))
        except:
            totalFamilyDF.append("#")
            
totalFamily_dfOut = [-1 if item=='#' else int(item) for item in totalFamilyDF]

In [315]:
# tf3 = tf3[tf3['Quality']==1]
# tf4 = tf4[tf4['Quality']==1]
totalFamily_df34 = pd.concat([tf3['DF entity'], tf4['DF entity']]).tolist()
for item in totalFamily_df34:
    try:
        if (type(int(item))==int):
            totalFamily_dfOut.append(int(item))
    except:
        totalFamily_dfOut.append(-1)

In [334]:
l1Act, l2Act = [], []
for item in totalFamily_gt:
    try:
        if (type(int(item)) == int):
            l1Act.append(1)
            l2Act.append(int(item))
    except:
            l1Act.append(0)
            l2Act.append(-1)

l1Out = []
for item in totalFamily_out:
    if item==-1:
        l1Out.append(0)
    else:
        l1Out.append(1)

In [329]:
l1Out = []
for item in totalFamily_dfOut:
    if item==-1:
        l1Out.append(0)
    else:
        l1Out.append(1)

In [337]:
from sklearn.metrics import accuracy_score, precision_score, f1_score, recall_score, confusion_matrix
print(precision_score(l1Act,l1Out))
print(f1_score(l1Act,l1Out))
print(recall_score(l1Act, l1Out))
print("Presence Identification accuracy is ",accuracy_score(l1Act, l1Out))
print("Correctness accuracy is ",accuracy_score(l2Act,totalFamily_out))

0.9562043795620438
0.8911564625850341
0.8343949044585988
Presence Identification accuracy is  0.8174904942965779
Correctness accuracy is  0.7604562737642585


In [336]:
print(confusion_matrix(l1Act, l1Out))

[[ 37  18]
 [ 78 393]]


<b>Accuracy Combined</b> 

In [243]:
numberOut = months_pregnant_out + noOfChildren_out + totalFamily_out
numberAct = months_pregnant_act + noOfChildren_act + totalFamily_act
numberDF = months_pregnant_dfOut + noOfChildren_dfOut + totalFamily_dfOut

In [244]:
print(len(numberAct), len(numberOut), len(numberDF))

748 748 748


In [245]:
print("Number Accuracy for our module is ",accuracy_score(numberAct, numberOut))
print("Number Accuracy for Dialogflow is ", accuracy_score(numberAct, numberDF))

Number Accuracy for our module is  0.9572192513368984
Number Accuracy for Dialogflow is  0.9037433155080213


# Yes/No

In [402]:
yn12 = pd.read_excel('haaNaTrain.xlsx')
yn3 = pd.read_excel('yesNoR3.xlsx')
yn4 = pd.read_excel('yesNoR4.xlsx')

print(yn12.shape, yn3.shape, yn4.shape)

(249, 7) (206, 7) (108, 7)


In [403]:
haaNa = pd.concat([yn12, yn3, yn4])
print(haaNa.shape)
haaNa = haaNa[haaNa['Quality']==1]
print(haaNa.shape)

(563, 7)
(504, 7)


In [404]:
"""
This script takes the user query as input and computes a
semantic search between the words in the Yes list and No
list to return if the user wanted to say 'Yes' or 'No' to the
question (or perhaps 'Maybe').
Reference : https://github.com/UKPLab/sentence-transformers/blob/master/examples/applications/semantic_search.py
"""
import argparse
import os
import sys
import torch

from sentence_transformers import SentenceTransformer, util

embedder = SentenceTransformer('distiluse-base-multilingual-cased')

def get_edit_distance_score():
    return

def get_semantic_score(query):
    """
        0 : No
        1 : Yes
        2 : Maybe
    """

    mapping_codes = {
        0:'No',
        1:'Yes'
    }

    # Corpus with example sentences
    corpus = {'हाँजी बिलकुल है': 1,
              'हाँजी': 1,
              'हाँ': 1,
              'हाँ घर में गर्वभती महिला है': 1,
              'नहीं': 0,
              'बिलकुल नहीं': 0,
              'नहीं घर में गर्वभती महिला नहीं है': 0,
              }

    corpus_questions = list(corpus.keys())
    corpus_embeddings = embedder.encode(corpus_questions, convert_to_tensor=True)

    # Find the closest 1 sentences of the corpus for query sentence based on cosine similarity
    top_k = 1       # NOTE: Provide as a command line argument
    query_embedding = embedder.encode(query, convert_to_tensor=True)
    cos_scores = util.pytorch_cos_sim(query_embedding, corpus_embeddings)[0]
    cos_scores = cos_scores.cpu()

    # Use torch.topk to find the highest 5 scores
    top_results = torch.topk(cos_scores, k=top_k)

#     print("\n\n======================\n\n")
#     print("Query:", query)
    # print("\nTop most similar sentences in corpus:")

    # for score, idx in zip(top_results[0], top_results[1]):
    #     print(corpus_questions[idx], "(Score: %.4f)" % (score))
    
#     print(top_results)
#     return top_results
#     print("Final Answer : {}".format(mapping_codes[corpus[corpus_questions[top_results[1]]]]))
#     return mapping_codes[corpus[corpus_questions[top_results[1]]]]
    
#     print("****************************************************************************")
#     print(mapping_codes[corpus[corpus_questions[top_results[1]]]])
#     print("############################################################################")
    out = str(mapping_codes[corpus[corpus_questions[top_results[1]]]])
#     print(out)
    return out

def bert_yes_no(query):
    semantic_score = get_semantic_score(query)
    return semantic_score
#     print("Semantic score : {}".format(semantic_score))
    # edit_distance_score = get_edit_distance_score()

    # avg_score = (semantic_score+edit_distance_score)/2

In [405]:
yesNoQues = haaNa['STT transcription']
yesNoValue = haaNa['Ground truth entity']

In [406]:
bertQ1Out = [bert_yes_no(text) for text in yesNoQues]
yesNoOut = [1 if item=='Yes' else 0 for item in bertQ1Out]
# print(bertQ1Out)

In [407]:
yesNoAct = []
for text in yesNoValue:
    if text=='Yes' or text=='yes' or text=='yes ' or text=='Yes ' or text==' Yes' or text==' yes':
        yesNoAct.append(1)
    elif text=='No' or text=='no' or text=='No ' or text=='no ' or text==' No' or text==' no':
        yesNoAct.append(0)
    else:
        yesNoAct.append(-1)

In [408]:
print(accuracy_score(yesNoAct, yesNoOut))

0.9920634920634921


In [388]:
l1YesNoAct, l1YesNoOut = [], []

for text in yesNoAct:
        if text==1 or text==0:
            l1YesNoAct.append(1)
        else:
            l1YesNoAct.append(0)

for text in yesNoOut:
    if text==1 or text==0:
        l1YesNoOut.append(1)
    else:
        l1YesNoOut.append(0)

In [389]:
print(confusion_matrix(l1YesNoAct, l1YesNoOut))

[[  0  24]
 [  0 539]]


In [390]:
print(precision_score(l1YesNoAct,l1YesNoOut))
print(f1_score(l1YesNoAct, l1YesNoOut))
print(recall_score(l1YesNoAct, l1YesNoOut))
print(accuracy_score(l1YesNoAct, l1YesNoOut))

0.9573712255772646
0.9782214156079855
1.0
0.9573712255772646


In [391]:
print(confusion_matrix(yesNoAct, yesNoOut))

[[  0   6  18]
 [  0 446  20]
 [  0   2  71]]


<b>Dialogflow for yes/no</b>

In [409]:
yn12 = yn12[yn12['Quality']==1]
q1DF = yn12['DF entity']

In [410]:
import json
q1Pred = []
for pred in q1DF:
        try:
            ent = json.loads(pred)
            q1Pred.append(str(list(ent['entity'][0].values())[0]))
        except:
            q1Pred.append(str(-1))
        

In [411]:
yesNoDFOut = [1 if item=='yes' else 0 if item=='no' else -1 for item in q1Pred]
print(yesNoDFOut)

[0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, -1, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 1, 0, 0, 0, 0, 1, 1, 0, -1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, -1, 0, 1, 0, 1, 0, 1, 0, -1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, -1, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, -1, 0, -1, -1, 0, 0, 0, 0, 0]


In [412]:
yn3 = yn3[yn3['Quality']==1]
yn4 = yn4[yn4['Quality']==1]
yesNo_df34 = pd.concat([yn3['DF entity'], yn4['DF entity']]).tolist()
for text in yesNo_df34:
    text = str(text)
    if text=='Yes' or text=='yes' or text=='yes ' or text=='Yes ' or text==' Yes' or text==' yes':
        yesNoDFOut.append(1)
    elif text=='No' or text=='no' or text=='No ' or text=='no ' or text==' No' or text==' no':
        yesNoDFOut.append(0)
    else:
        yesNoDFOut.append(-1)

In [413]:
l1YesNoAct, l1YesNoDFOut = [], []

for text in yesNoAct:
        if text==1 or text==0:
            l1YesNoAct.append(1)
        else:
            l1YesNoAct.append(0)

for text in yesNoDFOut:
    if text==1 or text==0:
        l1YesNoDFOut.append(1)
    else:
        l1YesNoDFOut.append(0)

In [418]:
print(accuracy_score(yesNoAct, yesNoDFOut))

0.9424603174603174


In [415]:
print(confusion_matrix(l1YesNoAct, l1YesNoDFOut))

[[  2   2]
 [ 18 482]]


In [416]:
print(confusion_matrix(yesNoAct, yesNoDFOut))

[[  2   0   2]
 [ 13 415   7]
 [  5   2  58]]


In [417]:
print(precision_score(l1YesNoAct,l1YesNoDFOut))
print(f1_score(l1YesNoAct, l1YesNoDFOut))
print(recall_score(l1YesNoAct, l1YesNoDFOut))
print(accuracy_score(l1YesNoAct, l1YesNoDFOut))

0.9958677685950413
0.9796747967479674
0.964
0.9603174603174603


# Age

In [147]:
umra12 = pd.read_excel('ageR12.xlsx')
umra3 = pd.read_excel('ageR3.xlsx')
umra4 = pd.read_excel('ageR4.xlsx')

In [121]:
print(umra12.shape, umra3.shape, umra4.shape)

(119, 7) (143, 7) (39, 7)


In [148]:
age = pd.concat([umra12, umra3, umra4])
print(age.shape)
age = age[age['Quality']==1]
print(age.shape)

(301, 7)
(240, 7)


In [149]:
import textdistance as td

thresh = 0.80

def preprocess_date(sent):
    hi_nums = ['शून्य','एक','दो','तीन','चार','पांच','छः','सात','आठ','नौ','दस','ग्यारह','बारह','तेरह','चौदह',
             'पंद्रह','सोलह','सत्रह','अट्ठारह','उन्निस','बीस','इक्कीस','बाईस','तेईस','चौबीस','पच्चीस','छब्बीस','सत्ताईस','अट्ठाईस','उनतीस','तीस','इकतीस',
             'बत्तीस','तैंतीस','चौंतीस','पैंतीस','छ्त्तीस','सैंतीस','अड़तीस','उनतालीस','चालीस','इकतालीस','बयालीस','तैंतालीस','चौंतालीस',
             'पैंतालीस','छियालीस','सैंतालीस','अड़तालीस','उनचास','पचास','इक्याबन','बावन','तिरेपन','चौबन','पचपन','छप्पन','सत्तावन',
            'अट्ठावन','उनसठ','साठ','इकसठ','बासठ','तिरसठ','चौंसठ','पैंसठ','छियासठ','सड़सठ','अड़सठ','उनहत्तर','सत्तर','इकहत्तर',
            'बहत्तर','तिहत्तर','चौहत्तर','पचहत्तर','छिहत्तर','सतहत्तर','अठहत्तर','उनासी','अस्सी','इक्यासी','बयासी','तिरासी','चौरासी',
             'पचासी','छियासी','सतासी','अठासी' ,'नवासी','नब्बे','इक्यानबे','बानवे','तिरानवे','चौरानवे','पचानवे','छियानवे','सत्तानवे',
             'अट्ठानवे','निन्यानवे' ,'सौ']
    
    pos_words = {'डेढ़':'1 साल 6 महीना', 'ढाई':'2 साल 6 महीना','डाइट':'2 साल 6 महीना', 'चार्ट':'साल', 'वर्स':'साल',
                 'वर्ष':'साल', 'नव':'9','नाना':'9', 'चैप्टर':'4', 'वाट':'साल'}
    
    sent = str(sent)
    words = sent.split(' ')
    out_sent = []
    for idx, word in enumerate(words):    
        for pw_idx, pos_word in enumerate(hi_nums):
            if td.levenshtein.normalized_similarity(pos_word, word) >= thresh:
                words[idx] = str(pw_idx)
        for pos_word in pos_words:
            if td.levenshtein.normalized_similarity(pos_word, word) >= thresh:
                words[idx] = pos_words[pos_word]
    
    words = ' '.join(words)
#     print(words)
    return words

In [150]:
# Final logic of date extraction
import re
import datetime
from dateparser.search import search_dates
from dateutil.relativedelta import relativedelta

out_dates = []    # This is the DoB
ages = []
curr_date = datetime.datetime.now()

for sent in age['STT transcription']:
    sent = preprocess_date(sent)
    out = search_dates(sent)
    if out == None and re.search('\d+', sent) != None:
        idx = re.search('\d+', sent).end()
        out = search_dates(sent[:idx]+' साल'+sent[idx:])
    out_date = []
    ageTemp = []
    if out != None:
        for o in out:
            out_date.append(str(o[1].year) + ' years ' + str(o[1].month) + ' months ' + str(o[1].day) + ' days')
            age_diff = relativedelta(curr_date.date(),o[1].date())
            ageTemp.append(str(age_diff.years) + ' years ' + str(age_diff.months) + ' months ' + str(age_diff.days) + ' days ')
    out_dates.append(','.join(out_date))
    ages.append(','.join(ageTemp))
# print(out_dates)
# print(ages)

In [151]:
ageOutDin, ageOutMahina, ageOutSaal = [], [], []
times = 0
for sentence in ages:
#     print(sentence)
    items = sentence.split()
    if len(items) > 0:
        yInd = items.index('years')
        dInd = items.index('days')
        mInd = items.index('months')
        ageOutDin.append(int(items[dInd-1]))
        ageOutMahina.append(int(items[mInd-1]))
        ageOutSaal.append(int(items[yInd-1]))
    else:
        times += 1
        ageOutDin.append(-1)
        ageOutMahina.append(-1)
        ageOutSaal.append(-1)

# print(ageOutDin)
# print(ageOutMahina)
# print(ageOutSaal)

In [152]:
print(times)

12


In [153]:
# # text = 21/01/01
# text = '<noinfo>'
# from datetime import datetime
# try:
#     curr_date = datetime.now()
#     tempDate = datetime.strptime(text, '%d/%m/%y')
#     print(tempDate)
#     age_diff = relativedelta(curr_date.date(),tempDate.date())
#     print(str(age_diff.years) + ' years ' + str(age_diff.months) + ' months ' + str(age_diff.days) + ' days ')
# except:
#     print("Kuch bhi nahi hua hai")


In [154]:
# Preferable date format for age data is dd/mm/yy 
ageGT = age['Ground truth entity'].to_numpy()
from datetime import datetime
ageActDin , ageActMahina, ageActSaal = [], [], []
for sentence in ageGT:
    sentence = str(sentence)
    try:
        curr_date = datetime.now()
        tempDate = datetime.strptime(text, '%d/%m/%y')
#         print(tempDate)
        age_diff = relativedelta(curr_date.date(),tempDate.date())
        ageActDin.append(age_diff.days)
        ageActMahina.append(age_diff.months)
        ageActSaal.append(age_diff.years)
        print(str(age_diff.years) + ' years ' + str(age_diff.months) + ' months ' + str(age_diff.days) + ' days ')
    except:
        sentence = sentence.replace(","," ")
        items = sentence.split()
    
        if len(items)==1:
            ageActSaal.append(-1)
            ageActMahina.append(-1)
            ageActDin.append(-1)
            continue

        if "years" in items:
    #         print("aaya kay")
            inY = items.index("years")
            ageActSaal.append(int(items[inY-1]))
        elif "Years" in items:
            inY = items.index("Years")
            ageActSaal.append(int(items[inY-1]))
        else:
            ageActSaal.append(0)

        if "months" in items:
            inM = items.index("months")
            ageActMahina.append(int(items[inM-1]))
        elif "Months" in items:
            inM = items.index("Months")
            ageActMahina.append(int(items[inM-1]))
        else:
            ageActMahina.append(0)

        if "days" in items:
            inD = items.index("days")
            ageActDin.append(int(items[inD-1]))
        elif "Days" in items:
            inD = items.index("Days")
            ageActDin.append(int(items[inD-1]))
        else:
            ageActDin.append(0)

<b> Dialogflow for age </b>

In [155]:
umra12 = umra12[umra12['Quality']==1]
umra12DF = umra12['DF entity']

In [156]:
import json
umra12DFPred = []
for pred in umra12DF:
        try:
            ent = json.loads(pred)
            umra12DFPred.append(str(list(ent['entity'][0].values())[0]))
        except:
            umra12DFPred.append('NOENTITY')

In [157]:
umra3 = umra3[umra3['Quality']==1]
umra4 = umra4[umra4['Quality']==1]
umra_df34 = pd.concat([umra3['DF entity'], umra4['DF entity']]).tolist()

In [158]:
ageDF = umra12DFPred + umra_df34

In [159]:
start = 0
ageDFDin, ageDFMahina, ageDFSaal = [], [], []
for sentence in ageDF:
    print(start)
    start += 1
    sentence = str(sentence)
#     print(sentence)
    sentence = sentence.replace(","," ")
    items = sentence.split()
    
    if len(items)==1:
        try:
            if items[0]=='nan' or items[0]=='NOENTITY':
                ageDFSaal.append(-1)
                ageDFMahina.append(-1)
                ageDFDin.append(-1)
                continue
            else :
                ageDFSaal.append(int(items[0]))
                ageDFMahina.append(0)
                ageDFDin.append(0)
            continue
        except:
            ageDFSaal.append(-1)
            ageDFMahina.append(-1)
            ageDFDin.append(-1)
            continue
        
    if "years" in items:
#         print("aaya kay")
        inY = items.index("years")
        ageDFSaal.append(int(items[inY-1]))
    elif "Years" in items:
        inY = items.index("Years")
        ageDFSaal.append(int(items[inY-1]))
    elif "Year" in items:
        inY = items.index("Year")
        ageDFSaal.append(int(items[inY-1]))
    elif "year" in items:
        inY = items.index("year")
        ageDFSaal.append(int(items[inY-1]))
    else:
        ageDFSaal.append(0)
        
    if "months" in items:
        inM = items.index("months")
        ageDFMahina.append(int(items[inM-1]))
    elif "Months" in items:
        inM = items.index("Months")
        ageDFMahina.append(int(items[inM-1]))
    elif "Month" in items:
        inM = items.index("Month")
        ageDFMahina.append(int(items[inM-1]))
    elif "month" in items:
        inM = items.index("month")
        ageDFMahina.append(int(items[inM-1]))
    else:
        ageDFMahina.append(0)
        
    if "days" in items:
        inD = items.index("days")
        ageDFDin.append(int(items[inD-1]))
    elif "Days" in items:
        inD = items.index("Days")
        ageDFDin.append(int(items[inD-1]))
    elif "Day" in items:
        inD = items.index("Day")
        ageDFDin.append(int(items[inD-1]))
    elif "day" in items:
        inD = items.index("day")
        ageDFDin.append(int(items[inD-1]))
    else:
        ageDFDin.append(0)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239


In [160]:
print("Din accuracy ",accuracy_score(ageActDin, ageDFDin))
print("Mahina Accuarcy ",accuracy_score(ageActMahina, ageDFMahina))
print("Saal Accuracy ", accuracy_score(ageActSaal, ageDFSaal))
# print(len(ageActDin))
print(len(ageOutDin))

Din accuracy  0.725
Mahina Accuarcy  0.7208333333333333
Saal Accuracy  0.7125
240


In [161]:
l1DinAct = [0 if item<=0 else 1 for item in ageActDin]
l1MahinaAct = [0 if item==0 else 1 for item in ageActMahina]
l1SaalAct = [0 if item==0 else 1 for item in ageActSaal]
l1DOut = [0 if item<=0 else 1 for item in ageDFDin]
l1MonthOut = [0 if item==0 else 1 for item in ageDFMahina]
l1YearOut = [0 if item==0 else 1 for item in ageDFSaal]
print(confusion_matrix(l1DinAct, l1DOut))
print(confusion_matrix(l1MahinaAct, l1MonthOut))
print(confusion_matrix(l1SaalAct, l1YearOut))

[[234   0]
 [  0   6]]
[[139  61]
 [  0  40]]
[[ 17  14]
 [  0 209]]


In [165]:
print(precision_score(l1DinAct,l1DOut))
print(f1_score(l1DinAct, l1DOut))
print(recall_score(l1DinAct, l1DOut))
print(accuracy_score(l1DinAct, l1DOut))

1.0
1.0
1.0
1.0


In [166]:
print(precision_score(l1MahinaAct,l1MonthOut))
print(f1_score(l1MahinaAct, l1MonthOut))
print(recall_score(l1MahinaAct, l1MonthOut))
print(accuracy_score(l1MahinaAct, l1MonthOut))

0.39603960396039606
0.5673758865248227
1.0
0.7458333333333333


In [167]:
print(precision_score(l1SaalAct,l1YearOut))
print(f1_score(l1SaalAct, l1YearOut))
print(recall_score(l1SaalAct, l1YearOut))
print(accuracy_score(l1SaalAct, l1YearOut))

0.9372197309417041
0.9675925925925926
1.0
0.9416666666666667
